[package]
name = "assembler"
version = "0.1.0"
authors = ["gipsond <david.gipson@utexas.edu>"]
edition = "2018"

[dependencies]
nom = "5.0.1"
lc3-isa = { path = "../../isa", version = "0.1.0", default-features = false, features = ["no_std"] }
